"""ajout records puissance seance

Revision ID: acb7b0832feb
Revises: 0001
Create Date: 2026-08-15 22:06:08.617566

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "acb7b0832feb"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("seance", sa.Column("puissance_max_1min", sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column("seance", sa.Column("puissance_max_3min", sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column("seance", sa.Column("puissance_max_5min", sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column("seance", sa.Column("puissance_max_10min", sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column("seance", sa.Column("puissance_max_20min", sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column("seance", sa.Column("flux_puissance_traite_le", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seance", "flux_puissance_traite_le")
    op.drop_column("seance", "puissance_max_20min")
    op.drop_column("seance", "puissance_max_10min")
    op.drop_column("seance", "puissance_max_5min")
    op.drop_column("seance", "puissance_max_3min")
    op.drop_column("seance", "puissance_max_1min")
    # ### end Alembic commands ###
